name: DIGI-Admin deployment Script

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH and Run Script
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: 147.93.107.50
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
           pwd
            ./deploy.sh
